## Numerical PDEs: 2D Laplace Equation

In [2]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


D:\Anaconda\lib\site-packages\IPython\core\magics\pylab.py:160: UserWarning: pylab import has clobbered these variables: ['e']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [3]:
# exact matrix inversion
A = [[4, -1, -1, 0, 0, 0],[-1, 4, 0, 0, -1, 0],[-1, 0, 4, -1, -1, 0],[0, 0, -2, 4, 0, -1], [0, -1, -1, 0, 4, -1], [0, 0, 0, -2, -2, 4]]
b = [150, 30, 90, 90, 0, 0]
x_true = np.linalg.solve(A, b)
print(x_true)

[61.57175399 32.18678815 64.10022779 67.65375854 37.17539863 52.41457859]


In [5]:
def seidel(a, x ,b): 
    #Finding length of a(3)        
    n = len(a)                    
    # for loop for 3 times as to calculate x, y , z 
    for j in range(0, n):         
        # temp variable d to store b[j] 
        d = b[j]                   
          
        # to calculate respective xi, yi, zi 
        for i in range(0, n):      
            if(j != i): 
                d-=a[j][i] * x[i] 
        # updating the value of our solution         
        x[j] = d / a[j][j] 
    # returning our updated solution            
    return x     
   
# int(input())input as number of variable to be solved                                            
a = []                             
b = []         
# initial solution depending on n(here n=3)                      
x = [0, 0, 0, 0, 0, 0] #input the starting guesses                      
a = [[4, -1, -1, 0, 0, 0],[-1, 4, 0, 0, -1, 0],[-1, 0, 4, -1, -1, 0],[0, 0, -2, 4, 0, -1], [0, -1, -1, 0, 4, -1], [0, 0, 0, -2, -2, 4]] #matrixA
b = [150, 30, 90, 90, 0, 0] #vecb
n = len(b)
print("Initial x values:",x) 

es = 0.01 # desired error
e = [2000, 10000, 9000, 8000] # initial large errors
#loop run for m times depending on m the error value
N = 100 #max loops = 100 to stop diverging
while min(e) > es and N > 0:             
    x = seidel(a, x, b) 
    #print each time the updated solution 
    print("x_values:",x)
    for i in range(0, len(e)):
        e[i] = abs((x[i] - x_true[i])/x_true[i])
    N -= 1    
    print("relative error",e)

Initial x values: [0, 0, 0, 0, 0, 0]
x_values: [37.5, 16.875, 31.875, 38.4375, 12.1875, 25.3125]
relative error [0.3909544950055494, 0.47571656050955413, 0.5027318763326226, 0.43184974747474736]
x_values: [49.6875, 22.96875, 47.578125, 52.6171875, 23.96484375, 38.291015625]
relative error [0.19301470588235295, 0.2863919851380042, 0.25775419776119396, 0.22225773358585846]
x_values: [55.13671875, 27.275390625, 55.4296875, 59.78759765625, 30.2490234375, 45.018310546875]
relative error [0.10451278093784684, 0.15259048235137998, 0.13526535847547969, 0.11627086292613621]
x_values: [58.17626953125, 29.6063232421875, 59.55322265625, 63.53118896484375, 33.544464111328125, 48.53782653808594]
relative error [0.055146787857241954, 0.08017155673600047, 0.07093586545509055, 0.06093629779237674]
x_values: [59.789886474609375, 30.833587646484375, 61.71638488769531, 65.49264907836914, 35.271949768066406, 50.38229942321777]
relative error [0.028939690626950957, 0.0420421106293955, 0.03718930470155493, 0

In [31]:
def jacobi(A,b,N,x,tol):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = diag(A)
    R = A - diagflat(D)

        # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x2 = (b - dot(R,x)) / D
        delta = np.linalg.norm(x - x2)
        print(x2)
        if delta < tol:
            return x2
        x = x2

    warnings.warn(f"did not converge within {N} iterations")

    return x

In [32]:
a = [[4, -1, -1, 0],[-1, 4, 0, -1],[-1, 0, 4, -1], [0, -1, -1, 4]]
b = [2, 44, 44, -238]
x = [0, 0, 0, 0]
N = 100
tol = 0.01
jacobi(A, b, N, x,tol)

[  0.5  11.   11.  -59.5]
[  6.    -3.75  -3.75 -54.  ]
[ -1.375  -1.     -1.    -61.375]
[  0.      -4.6875  -4.6875 -60.    ]
[ -1.84375  -4.       -4.      -61.84375]
[ -1.5       -4.921875  -4.921875 -61.5     ]
[ -1.9609375  -4.75       -4.75      -61.9609375]
[ -1.875       -4.98046875  -4.98046875 -61.875     ]
[ -1.99023438  -4.9375      -4.9375     -61.99023438]
[ -1.96875     -4.99511719  -4.99511719 -61.96875   ]
[ -1.99755859  -4.984375    -4.984375   -61.99755859]
[ -1.9921875  -4.9987793  -4.9987793 -61.9921875]
[ -1.99938965  -4.99609375  -4.99609375 -61.99938965]
[ -1.99804688  -4.99969482  -4.99969482 -61.99804688]


array([ -1.99804688,  -4.99969482,  -4.99969482, -61.99804688])