## Explicit Methods

In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


Input the initial time, the duration, the time step and the initial y value.

1st Order Differential Function

In [2]:
def f(tn, yn):
    fn = 1 + tn**2 + yn
    return fn

Forward Euler Method

In [3]:
def FwEuler(t0, y0, h, t_end):
    tn = np.arange(t0, t_end+h, h) # create lists
    yn = np.ndarray(len(tn)) # create output array
    tn[0] = t0 #set initial values
    yn[0] = y0
    for i in range(1, len(tn)):
        yn[i] = yn[i-1] + h*f(tn[i-1], yn[i-1])
        print([i], "yn:", yn[i-1], "tn:", tn[i-1], "yn+1:", yn[i])
    return yn, tn

In [4]:
t0 = 0
t_end = 0.8
h = 0.2
y0 = 1
FwEuler(t0, y0, h, t_end)

[1] yn: 1.0 tn: 0.0 yn+1: 1.4
[2] yn: 1.4 tn: 0.2 yn+1: 1.888
[3] yn: 1.888 tn: 0.4 yn+1: 2.4976
[4] yn: 2.4976 tn: 0.6000000000000001 yn+1: 3.26912


(array([1.     , 1.4    , 1.888  , 2.4976 , 3.26912]),
 array([0. , 0.2, 0.4, 0.6, 0.8]))

4th Order Runge-Kutta Method

In [5]:
def RK4(t0, y0, h, t_end):
    tn = np.arange(t0, t_end+h, h)
    yn = np.ndarray(len(tn)) # create output array
    
    tn[0] = t0
    yn[0] = y0
    
    k1n = 0
    k2n = 0
    k3n = 0
    k4n = 0
    for i in range(1, len(tn)):
        k1n = h*f(tn[i-1], yn[i-1])
        k2n = h*f(tn[i-1] + 0.5*h, yn[i-1] + 0.5*k1n)
        k3n = h*f(tn[i-1] + 0.5*h, yn[i-1] + 0.5*k2n)
        k4n = h*f(tn[i-1] + h, yn[i-1] + k3n)
        yn[i] = yn[i-1] + (1/6)*(k1n + 2*k2n + 2*k3n + k4n)
        
        print([i], "yn:", yn[i-1], "tn:", tn[i-1], "k1n:", k1n, "k2n:", k2n, "k3n:", k3n, "k4n:", k4n, "yn+1:", yn[i])
    return (yn, tn)

In [6]:
t0 = 0
t_end = 50
h = 5
y0 = 100
RK4(t0, y0, h, t_end)

[1] yn: 100.0 tn: 0 k1n: 505.0 k2n: 1798.75 k3n: 5033.125 k4n: 25795.625 yn+1: 6760.729166666666
[2] yn: 6760.729166666666 tn: 5 k1n: 33933.64583333333 k2n: 118924.01041666664 k3n: 331399.92187499994 k4n: 1691308.255208333 yn+1: 444409.02343749994
[3] yn: 444409.02343749994 tn: 10 k1n: 2222550.1171874995 k2n: 7779206.660156249 k3n: 21670848.01757812 k4n: 110577415.20507811 yn+1: 29061088.136393223
[4] yn: 29061088.136393223 tn: 15 k1n: 145306570.68196613 k2n: 508573403.6368814 k3n: 1416740486.0241697 k4n: 7229009875.8028145 yn+1: 1899885125.7708738
[5] yn: 1899885125.7708738 tn: 20 k1n: 9499427633.854368 k2n: 33247997249.74029 k3n: 92619421289.4551 k4n: 472596535206.1298 yn+1: 124205018445.50003
[6] yn: 124205018445.50003 tn: 25 k1n: 621025095357.5001 k2n: 2173587834407.5005 k3n: 6054994682032.501 k4n: 30895998506895.004 yn+1: 8119903124300.918
[7] yn: 8119903124300.918 tn: 30 k1n: 40599515626009.59 k2n: 142098304691814.8 k3n: 395845277356327.9 k4n: 2019825902409274.0 yn+1: 53083866681

(array([1.00000000e+02, 6.76072917e+03, 4.44409023e+05, 2.90610881e+07,
        1.89988513e+09, 1.24205018e+11, 8.11990312e+12, 5.30838667e+14,
        3.47035778e+16, 2.26874640e+18, 1.48319296e+20]),
 array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50]))

Heun's Method

In [7]:
def Heun(t0, y0, h, t_end):
    tn = np.arange(t0, t_end+h, h)
    yn = np.ndarray(len(tn)) # create output array
    
    tn[0] = t0
    yn[0] = y0
    
    k1n = 0
    k2n = 0
    for i in range(1, len(tn)):
        k1n = h*f(tn[i-1], yn[i-1])
        k2n = h*f(tn[i-1] + h, yn[i-1] + k1n)
        yn[i] = yn[i-1] + 0.5*(k1n + k2n)
        
        print([i], "yn:", yn[i-1], "tn:", tn[i-1], "k1n:", k1n, "k2n:", k2n, "yn+1:", yn[i])
    return

In [8]:
t0 = 0
t_end = 50
h = 5
y0 = 100
Heun(t0, y0, h, t_end)

[1] yn: 100.0 tn: 0 k1n: 505.0 k2n: 3155.0 yn+1: 1930.0
[2] yn: 1930.0 tn: 5 k1n: 9780.0 k2n: 59055.0 yn+1: 36347.5
[3] yn: 36347.5 tn: 10 k1n: 182242.5 k2n: 1094080.0 yn+1: 674508.75
[4] yn: 674508.75 tn: 15 k1n: 3373673.75 k2n: 20242917.5 yn+1: 12482804.375
[5] yn: 12482804.375 tn: 20 k1n: 62416026.875 k2n: 374497286.25 yn+1: 230939460.9375
[6] yn: 230939460.9375 tn: 25 k1n: 1154700434.6875 k2n: 6928203983.125 yn+1: 4272391669.84375
[7] yn: 4272391669.84375 tn: 30 k1n: 21361962854.21875 k2n: 128171778750.3125 yn+1: 79039262472.10938
[8] yn: 79039262472.10938 tn: 35 k1n: 395196318490.5469 k2n: 2371177912818.2812 yn+1: 1462226378126.5234
[9] yn: 1462226378126.5234 tn: 40 k1n: 7311131898637.617 k2n: 43866791393950.7 yn+1: 27051188024420.684
[10] yn: 27051188024420.684 tn: 45 k1n: 135255940132233.42 k2n: 811535640795775.5 yn+1: 500446978488425.1


Adams Bashford

In [9]:
def func(tn, yn):
    return np.exp(-4*tn)*tn*np.sin(tn)*np.sqrt(10*yn)

In [10]:
def AdamsBashford(t0, y0, f0, h, t_end):
    tn = np.arange(t0, t_end+h, h)
    yn = np.ndarray(len(tn))
    fn = np.ndarray(len(tn))
    
    tn[0] = 0
    yn[:4] = y0
    fn[:4] = f0
    
    for i in range(4, len(tn)):
        yn[i] = yn[i-1] + (h/24)*(55*fn[i-1] - 59*fn[i-2] + 37*fn[i-3] - 9*fn[i-4])
        fn[i] = func(tn[i], yn[i])
        
        print([i], "yn:", yn[i-1], "yn+1:", yn[i])
    return (yn, tn)

In [11]:
y0 = [8, 8.0022, 8.0132, 8.0335]
f0 = [0, 0.05986, 0.15982, 0.23934]
t0 = 0
t_end = 0.5
h = 0.1
AdamsBashford(t0, y0, f0, h, t_end)

[4] yn: 8.0335 yn+1: 8.058288083333334
[5] yn: 8.058288083333334 yn+1: 8.086540594796023


(array([8.        , 8.0022    , 8.0132    , 8.0335    , 8.05828808,
        8.08654059]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5]))

System of Linear ODEs using the Forward Euler Method

In [12]:
def F1(t, Y0):
    f1 = Y0[1]
    return f1

def F2(t, Y0):
    f2 = -3*Y0[1] - 2*Y0[0]
    return f2

In [13]:
def FwEulerTwo(t0, Y0, h, t_end):
    tn = np.arange(t0, t_end+h, h)
    Yn = np.ndarray([2, len(tn)]) # form an arbitrary output array (shape row by column)
    
    tn[0] = t0
    Yn[0,0] = Y0[0]
    Yn[1,0] = Y0[1]
    
    for i in range(1, len(tn)):
        Yn[0, i] = Yn[0, i-1] + h*F1(tn[i-1], Yn[:, i-1]) #function, F1
        Yn[1, i] = Yn[1, i-1] + h*F2(tn[i-1], Yn[:, i-1]) #function, F2
    return (tn, Yn)

In [14]:
t0 = 0
t_end = 40
h = 0.019
Y0 = [2, 3]
(tn, Yn) = FwEulerTwo(t0, Y0, h, t_end)
print(tn, Yn)

[0.0000e+00 1.9000e-02 3.8000e-02 ... 3.9976e+01 3.9995e+01 4.0014e+01] [[ 2.00000000e+00  2.05700000e+00  2.10930700e+00 ...  2.07343090e-17
   2.03403572e-17  1.99538904e-17]
 [ 3.00000000e+00  2.75300000e+00  2.51791300e+00 ... -2.07343090e-17
  -2.03403572e-17 -1.99538904e-17]]


Midpoint Method Q5b 2017

In [15]:
def MidpointSystem(t0, Y0, h, t_end):   
    tnhalf = np.arange(t0, (0.5*t_end)+0.5*h, 0.5*h)
    tn = np.arange(t0, t_end+h, h)
    Yn = np.ndarray([2, len(tn)]) # form an arbitrary output array (shape row by column)
    print(tnhalf, tn)
    
    tn[0] = t0
    tnhalf[0] = t0
    Yn[0,0] = Y0[0]
    Yn[1,0] = Y0[1]
    
    kni = 0
    knj = 0
    for i in range(1, len(tn)):
        kni = Yn[0, i-1] + (h/2)*F1(tn[i-1],Yn[:, i-1])
        knj = Yn[1, i-1] + (h/2)*F2(tn[i-1], Yn[:, i-1])
        
        Yn[0, i] = Yn[0, i-1] + h*F1(tnhalf[i-1], kni)
        Yn[1, i] = Yn[1, i-1] + h*F2(tnhalf[i-1], knj)
        print(Yn[0,i], Yn[1,i])
    return (tn, Yn)

In [16]:
t0 = 0
t_end = 0.02
h = 0.01
y0 = [1, 2]

In [20]:
def Midpoint(t0, y0, h, t_end):
    tn = np.arange(t0, t_end+h, h)
    yn = np.ndarray(len(tn))
    
    tn[0] = t0
    yn[0] = y0
    
    tnhalf = []
    for number in tn:
        tnhalf += [number + h/2]
    
    kni = 0
    for i in range(1, len(tn)):
        kni = yn[i-1] + (h/2)*f(tn[i-1],yn[i-1])
        yn[i] = yn[i-1] + h*f(tnhalf[i-1], kni)
        
        print([i-1], "yn:",yn[i-1], "tn:",tn[i-1], "tnhalf:",tnhalf[i-1], "yn+1:",yn[i])
    return

In [21]:
t0 = 0
t_end = 0.2
h = 0.1
y0 = 1
Midpoint(t0, y0, h, t_end)

[0] yn: 1.0 tn: 0.0 tnhalf: 0.05 yn+1: 1.21025
[1] yn: 1.21025 tn: 0.1 tnhalf: 0.15000000000000002 yn+1: 1.44462625
[2] yn: 1.44462625 tn: 0.2 tnhalf: 0.25 yn+1: 1.70776200625
